#!/usr/bin/env bash
set -euo pipefail

staged_files=$(git diff --cached --name-only -z --diff-filter=ACMR -- '*.ts' '*.tsx' '*.js' '*.jsx' '*.json')

if [ -z "$staged_files" ]; then
  exit 0
fi

echo -n "$staged_files" | xargs -0 bunx biome check --fix --diagnostic-level=warn

echo -n "$staged_files" | xargs -0 git add

echo -n "$staged_files" | xargs -0 bunx biome check --diagnostic-level=warn

bun --filter '*' check
