#!/usr/bin/env bash
set -euo pipefail

staged_files=$(git diff --cached --name-only --diff-filter=ACMR -- '*.ts' '*.tsx' '*.js' '*.jsx' '*.json')

if [ -z "$staged_files" ]; then
  exit 0
fi

echo "$staged_files" | xargs bunx biome check --fix --diagnostic-level=warn

echo "$staged_files" | xargs git add

echo "$staged_files" | xargs bunx biome check --diagnostic-level=warn

bun --filter '*' check
